version: '3'
services:
  mp-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mp-app:
    image: howlinbash/mp
    depends_on:
      - mp-db
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
