import Head from "next/head";
import React from "react";
import { ChannelToggles } from "~/components/channelToggles";
import { HotelSelect } from "~/components/hotelSelect";

import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.ui.getCurrentHotel.useQuery();

  console.log('home:', { data })
  return (
    <>
      <Head>
        <title>Meeting Package</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="text-white">
            <HotelSelect isStarting={isLoading} hotelId={data?.hotelId} />
            <ChannelToggles isStarting={isLoading} hotelId={data?.hotelId} />
          </div>
        </div>
      </main>
    </>
  );
}
