import Head from "next/head";
import React from "react";
import { Nunito } from "next/font/google";
import { ChannelTable } from "~/components/channelTable";
import { HotelSelect } from "~/components/hotelSelect";
import { api } from "~/utils/api";
import { MeetingPackageLogo } from "~/design/meetingPackageLogo";
import {
  CHANNEL_MANAGER_TITLE,
  MEETING_PACKAGE_URL,
  SITE_TITLE,
} from "~/constants";

const nunito = Nunito({
  subsets: ["cyrillic", "cyrillic-ext", "latin", "latin-ext", "vietnamese"],
});

export default function Home() {
  const { data, isLoading } = api.ui.getCurrentHotel.useQuery();

  return (
    <>
      <Head>
        <title>{SITE_TITLE}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex h-screen flex-col items-center ${nunito.className}`}
      >
        <header className="absolute inset-x-0 h-13 border-b border-gray-200">
          <div className="flex h-full flex-col items-center">
            <nav className="relative h-full w-full max-w-4/4">
              <div className="px-6 py-4">
                <a href={MEETING_PACKAGE_URL} className="outline-none">
                  <MeetingPackageLogo />
                </a>
              </div>
            </nav>
          </div>
        </header>
        <div className="mt-13 h-full w-full max-w-4/4 p-6">
          <h1 className="text-2xl font-semibold text-black">
            {CHANNEL_MANAGER_TITLE}
          </h1>
          <HotelSelect hotelId={data?.hotelId} />
          <ChannelTable isStarting={isLoading} hotelId={data?.hotelId} />
        </div>
      </main>
    </>
  );
}
